services:
  - type: web
    name: line-plus1-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    repo: https://github.com/hero011714/line-plus1-bot
    envVars:
      - key: CHANNEL_SECRET
        sync: false
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        value: "postgresql://postgres:t>vTPtZt9/QX@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
